### ISSUE TITLE
Would []byte be preferable?

### ISSUE THREAD

**Issue by joshq00** [adelowo/onecache#7]
Instead of interacting via empty interface, what are your thoughts on using `[]byte`? The user would take on the onus of [de]serialization and the skip the guessing game around type 

Cool project. I'll consider using it

**Comment by adelowo** [comment]
[I actually wanted that to use that](https://github.com/adelowo/onecache/commit/59fa7bf3d91916d2f9e0d57b0a7ca85a125f5999#diff-e871404fd69cab40521d6b2178847cf7R27) but i felt the [de]serialization would just be too much work for the user..

I already released a `1.0.0` so i don't think i would even be able to change that unless it would be bumped to `2.0.0`..

Thanks for considering this project.

**Comment by joshq00** [comment]
Fair, but if it means anything I'd (as a user) prefer type safety over convenience.

If I call `Set` with a `MyType{}`, should I expect `Get` to give back a `MyType`? If not, what type is it? `map[interface{}]interface{}`?

It's less complicated if I only use primitives, but am I limited to primitives without doing a ton of type assertion?

**Comment by adelowo** [comment]
`Get` would return an `interface{}` you can type assert (as `*MyType`).

Caveats

- You would have to register `MyType` with `encoding/gob` for it to work though.. `gob.Register(&MyType{})` should do

- For the redis store, `MyType` must implement `MarshalBinary() ([]byte, error)`.. Sounds pretty cumbersome.

You would still have to type assert - a little - since `Get` returns an `interface{}`

I would seriously consider making use of `[]byte` alone and leave the [de]serialization to the user..

**Comment by adelowo** [comment]
@joshq00 If this is complicated, please let me know... I should be able to convert it to make use of `[]byte`

**Comment by adelowo** [comment]
@joshq00 , I have thought this over and would implement it...

**Comment by adelowo** [comment]
@joshq00 I have started work on this [here](https://github.com/adelowo/onecache/tree/bytes)

**Comment by joshq00** [comment]
Awesome! Thanks!

**Comment by adelowo** [comment]
I have done this already... Here is an example of the new usage https://github.com/adelowo/onecache/blob/master/_examples/main.go

I also have tagged a new version https://github.com/adelowo/onecache/releases/tag/2.0.0
